stages:
  - containerization-x86
  - containerization-aarch64

variables:
  APPLICATION_NAME: image-storage
  CONTAINER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
  CONTAINER_IMAGE_DOCKER_HUB: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}

# Building application for X86 plattforms
containerization-x86:
  stage: containerization-x86
  tags:
    - "x86"
  script:
    # Docker hub login
    - >
    echo "${DOCKER_HUB_PASSWORD}"
    | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    # Building image
    - docker build -t ${CONTAINER_IMAGE} .
    # Tagging image for Docker Hub
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_DOCKER_HUB}
    # Pushing images
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_DOCKER_HUB}
    # Cleanup
    - docker image rm ${CONTAINER_IMAGE}
    - docker image rm ${CONTAINER_IMAGE_DOCKER_HUB}

# Building application for ARM (64bit) plattforms
containerization-aarch64:
  stage: containerization-aarch64
  tags:
    - "aarch64"
  script:
    - >
      docker build
      --build-arg HTTP_PROXY=http://172.16.98.151:8118
      --build-arg HTTPS_PROXY=http://172.16.98.151:8118
      -t ${CONTAINER_IMAGE}-aarch64 .
    - docker push ${CONTAINER_IMAGE}-aarch64
