stages:
  - build

variables:
  APPLICATION_NAME: image-storage-mongoose
  CONTAINER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}

# Building application for X86 plattforms
build-x86:
  stage: build
  tags:
    - x86
  script:
    - >
     if [ -z ${DOCKER_HUB_USERNAME} ];
     then echo "No Docker login" -;
     else echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin ;
     fi
    - docker build -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}
    # Cleanup
    - docker image rm ${CONTAINER_IMAGE}
