stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: storage

containerization:
  stage: containerization
  script:
    # Build and push container image (CONTAINER_REIGSTRY obtained from GitLab)
    - docker build -t ${CONTAINER_REGISTRY}/${APPLICATION_NAME} .
    - docker push ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
    # Cleanup
    - docker image rm ${CONTAINER_REGISTRY}/${APPLICATION_NAME}

deployment:
  stage: deployment
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: staging
    kubernetes:
      # namespace Obtained from GitLab
      namespace: ${KUBERNETES_NAMESPACE}
