stages:
  - containerization-x86
  - containerization-aarch64
  - deployment

variables:
  APPLICATION_NAME: image-storage

containerization-x86:
  stage: containerization-x86
  tags:
    - "x86"
  script:
    # Build and push container image (CONTAINER_REIGSTRY obtained from GitLab)
    - docker build -t ${CONTAINER_REGISTRY}/${APPLICATION_NAME} .
    - docker push ${CONTAINER_REGISTRY}/${APPLICATION_NAME}

containerization-aarch64:
  stage: containerization-aarch64
  tags:
    - "aarch64"
  script:
    - docker build -t ${CONTAINER_REGISTRY}/${APPLICATION_NAME}-aarch64 .
    - docker push ${CONTAINER_REGISTRY}/${APPLICATION_NAME}-aarch64

deployment:
  stage: deployment
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: staging
    kubernetes:
      # namespace Obtained from GitLab
      namespace: ${KUBERNETES_NAMESPACE}
