stages:
  - build
  - test

variables:
  APPLICATION_NAME: image-storage-mongoose
  CONTAINER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
  CONTAINER_IMAGE_DOCKER_HUB: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  TEST_NETWORK: tdd

build-x86:
  stage: build
  only:
    - master
  tags:
    - x86
  script:
    # - >
    #  if [ -z ${DOCKER_HUB_USERNAME} ];
    #  then echo "No Docker login" -;
    #  else echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin ;
    #  fi
    - docker build -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}
    # Cleanup
    - docker image rm ${CONTAINER_IMAGE}


# Building application for X86 plattforms
test:
  stage: test
  only:
    - master
  tags:
    - x86
  before_script:
    - echo "Deploying test database"
    # What is the h flag?
    - docker network create ${TEST_NETWORK}
    - docker run --rm -d --name tdd-db --network ${TEST_NETWORK} --hostname tdd-db mongo
    - echo "Database is up"
  script:
    # Run test
    - docker run --rm --name tdd-app --network ${TEST_NETWORK} ${CONTAINER_IMAGE} npm run test
