stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: tokushima-bearings-storage
  CONTAINER_REGISTRY: 172.16.98.151:5000

containerization:
  stage: containerization
  script:
    - docker build -t ${CONTAINER_REGISTRY}/${APPLICATION_NAME} .
    - docker push ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
    - docker image rm ${CONTAINER_REGISTRY}/${APPLICATION_NAME}

deployment:
  stage: deployment
  script:
    - kubectl apply -f deployment.yml
    - kubectl rollout restart deployment/${APPLICATION_NAME}-deployment
  environment:
    name: staging
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE} # Obtained from GitLab
