# Base image on node
FROM node:16

ENV HTTPS_PROXY="http://172.16.98.151:8118"
ENV HTTP_PROXY="http://172.16.98.151:8118"

# Create app directory and move into it
WORKDIR /usr/src/app

# Copy all files into container
COPY . .

# Install packages
RUN npm install

# Expose port
EXPOSE 80

# Run the app
CMD [ "node", "index.js" ]
