apiVersion: apps/v1
kind: Deployment
metadata:
    name: ${APPLICATION_NAME}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ${APPLICATION_NAME}
    template:
        metadata:
            labels:
                app: ${APPLICATION_NAME}
        spec:
            containers:
                - name: ${APPLICATION_NAME}
                  image: ${CONTAINER_IMAGE}
                  resources:
                      requests:
                          memory: 25Mi
                          cpu: 10m
                      limits:
                          memory: 1Gi
                          cpu: 10000m
---
apiVersion: v1
kind: Service
metadata:
    name: ${APPLICATION_NAME}
spec:
    type: NodePort
    selector:
        app: ${APPLICATION_NAME}
    ports:
        - port: 80
          nodePort: ${K8S_NODEPORT}
