apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-storage
  template:
    metadata:
      labels:
        app: image-storage
    spec:
      volumes:
      - name: image-storage
        persistentVolumeClaim:
          claimName: image-storage
      containers:
      - name: image-storage
        image: 172.16.98.151:5000/image-storage
        imagePullPolicy: Always
        env:
        - name: MONGODB_URL
          value: "mongodb://172.16.98.151:27017"
        - name: MONGODB_DB
          value: seikaibu_edge_ai
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/pv"
          name: image-storage
---
apiVersion: v1
kind: Service
metadata:
  name: image-storage
spec:
  ports:
  - port: 80
    nodePort: 31221
  selector:
    app: image-storage
  type: NodePort
