import dotenv from 'dotenv'
import swaggerAutogen from "swagger-autogen"
import { version, name } from "./package.json"

dotenv.config()
const generate = swaggerAutogen()
const {
  APP_PORT = 80,
} = process.env

const doc = {
  info: {
    version,
    title: name,
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: `localhost:${APP_PORT}`,
  basePath: "/",
  consumes: ["application/json"],
  produces: ["application/json"],
}

const outputFile = "./swagger-output.json"
const endpointsFiles = ["./index.ts"]

generate(outputFile, endpointsFiles, doc)
