import swaggerAutogen from "swagger-autogen"

const generate = swaggerAutogen()

const doc = {
  info: {
    version: "1.0.0",
    title: "Image storage service",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  basePath: "/",
  consumes: ["application/json"],
  produces: ["application/json"],
}

const outputFile = "./swagger-output.json"
const endpointsFiles = ["./index.ts"]

generate(outputFile, endpointsFiles, doc)
